name: clang-tidy

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  clang-tidy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: sudo apt-get install clang clang-tidy clang-format

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug

    - name: Check formatting
      run: |
        find . -name '*.cpp' -o -name '*.hpp' | xargs clang-format -style=file --dry-run -Werror

    - name: Run clang-tidy
      run: |
        cd build
        run-clang-tidy -p . -quiet 'src/*' 'inc/*'
