name: Windows Build

on:
  push:
    branches:
      - dev

jobs:
  windows-build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release, Debug]
        architecture: [x64, x86]
        compiler: [cl, clang++]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Run CMake Configure
      run: cmake cmake -S . -B build -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }} -A ${{ matrix.architecture }} -DKRA_IMP_BUILD_DOC=OFF
    - name: Build with CMake
      run: cmake --build build --config ${{ matrix.build_type }}
